### ISSUE TITLE
Some times are shown in user's local time

### ISSUE THREAD

**Issue by jonah0** [joerovar/rail-ops-app#10]
`arrT` and `prdt` values are displayed in the user's local time, instead of Chicago time. For instance, compare "Prd. Time" with "Schd. Time" below (I am on New York time):

<img width="819" alt="image" src="https://github.com/user-attachments/assets/0b426529-bc14-42cc-8b2d-a899a0233895">

The datetimes are still interpreted correctly, which is why the "Schd. Dev" values are correct, instead of showing a 1-hour delay.

@joerovar I think it is more useful to show all times in Chicago local time, but what do you think?

This can be solved by modifying the following function:
https://github.com/joerovar/rail-ops-app/blob/6a802bf734574cb4eded9b70e679aec3df044944/src/components/utils.js#L58-L60

```diff
export const formatTime = (datetime) => {
-  return moment(datetime).format('HH:mm');
+  return moment(datetime).tz('America/Chicago').format('HH:mm');
};
```

This was not an issue before because all `arrT` and `prdt` values were given as strings already in Chicago time but timezone-naive, so moment parsed them in the user's local time. But now the backend is returning them as date objects.

**Comment by joerovar** [comment]
@jonah0 thanks for highlighting this. just pushed the new changes.
